#!/bin/sh

if [ "$1" == "--clean-profile" ]; then
	rm -rf ~/.TorBrowser/bookmarkbackups
	rm -rf ~/.TorBrowser/cache2
	rm -rf ~/.TorBrowser/datareporting
	rm -rf ~/.TorBrowser/healthreport
	rm -rf ~/.TorBrowser/saved-telemetry-pings
	rm -rf ~/.TorBrowser/storage
	rm -rf ~/.TorBrowser/startupCache
	rm -rf ~/.TorBrowser/pluginreg.dat
	rm -rf ~/.TorBrowser/cookies.sqlite
	rm -rf ~/.TorBrowser/permissions.sqlite
	rm -rf ~/.TorBrowser/formhistory.sqlite
	rm -rf ~/.TorBrowser/healthreport.sqlite
	rm -rf ~/.TorBrowser/.parentlock
	rm -rf ~/.TorBrowser/SiteSecurityServiceState.txt
	rm -rf ~/.TorBrowser/adblockplus/patterns-backup*
	rm -rf ~/.TorBrowser/content-prefs.sqlite
	rm -rf ~/.TorBrowser/gmp
	rm -rf ~/.TorBrowser/webappsstore.sqlite
	rm -rf ~/.TorBrowser/sessionCheckpoints.json
	rm -rf ~/.TorBrowser/revocations.txt
	rm -rf ~/.TorBrowser/cert8.db
	rm -rf ~/.TorBrowser/key3.db
	rm -rf ~/.TorBrowser/webapps
	rm -rf ~/.TorBrowser/times.json
	rm -rf ~/.TorBrowser/search.json
	rm -rf ~/.TorBrowser/search-metadata.json
	rm -rf ~/.TorBrowser/secmod.db
	rm -rf ~/.TorBrowser/xulstore.json
	rm -rf ~/.TorBrowser/safebrowsing
	rm -rf ~/.TorBrowser/directoryLinks.json
	rm -rf ~/.TorBrowser/HTTPSEverywhereUserRules
	rm -rf ~/.TorBrowser/lightweighttheme-header
	rm -rf ~/.TorBrowser/lightweighttheme-footer
	rm -rf ~/.TorBrowser/frequencyCap.json
	rm -rf ~/.TorBrowser/mimeTypes.rdf
	rm -rf ~/.TorBrowser/compatibility.ini
	rm -rf ~/.TorBrowser/blocklist.xml
	exit 0
fi

# if the user does not have a TorBrowser profile
# create one
if [ ! -x ~/.TorBrowser ]; then
	mkdir -p ~/.TorBrowser;
	cp -R /usr/share/not-tor-browser/* ~/.TorBrowser
	chmod -R o-rwx ~/.TorBrowser
fi

# make sure the Tor daemon is running
/usr/bin/sudo /usr/bin/systemctl start tor;

# Using a system-installed Tor process with Tor Browser:
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# The Tor ControlPort password should be given inside double quotes, inside
# single quotes, i.e. if the ControlPort password is “secret” (without
# curly quotes) then we must set the environment variable *exactly* like
# this:
#
# TOR_CONTROL_PASSWD='"secret"'
#
# Yes, the variable MUST be double-quoted, then single-quoted, exactly as
# shown. This is used by TorButtom to authenticate to Tor's ControlPort, and
# is necessary for using TBB with a with a system-installed Tor.
#
# Additionally, if using a system-installed Tor, the following about:config
# options should be set (values in <> mean they are the value taken from your
# torrc):
#
# SETTING NAME                            VALUE
# extensions.torbutton.banned_ports       [...],<SocksPort>,<ControlPort>
# extensions.torbutton.block_disk         false
# extensions.torbutton.custom.socks_host  127.0.0.1
# extensions.torbutton.custom.socks_port  <SocksPort>
# extensions.torbutton.inserted_button    true
# extensions.torbutton.launch_warning     false
# extensions.torbutton.loglevel           2
# extensions.torbutton.logmethod          0
# extensions.torbutton.settings_method    custom
# extensions.torbutton.socks_port         <SocksPort>
# extensions.torbutton.use_privoxy        false
# extensions.torlauncher.control_port      <ControlPort>
# extensions.torlauncher.loglevel          2
# extensions.torlauncher.logmethod         0
# extensions.torlauncher.prompt_at_startup false
# extensions.torlauncher.start_tor         false
#
# where the '[...]' in the banned_ports option means "leave anything that was
# already in the preference alone, just append the things specified after it".

# Either set `TOR_CONTROL_PASSWD` before running ./start-tor-browser, or put
# your password in the following line where the word “secret” is:

# start firefox with the Tor profile
export TOR_CONTROL_PASSWD='"secret"'
exec /usr/bin/firefox \
	--no-remote \
	--profile ~/.TorBrowser
